version: 2
project_name: raido

before:
  hooks:
    - go mod tidy
    - make clean

builds:
  - main: ./cmd/agent
    id: "agent"
    binary: agent
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - linux
      # - darwin
      # - windows
    goarch:
      - amd64
      - arm
      - arm64
  - main: ./cmd/raido
    id: "raido"
    binary: raido
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - linux
      # - darwin
      # - windows
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - 
    id: "raido"
    builds: ['raido']
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
  - 
    id: "agent"
    builds: ['agent']
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github-native
